# Generated by Django 6.0.2 on 2026-02-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image2', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('download_link', models.FileField(blank=True, null=True, upload_to='game_downloads/')),
            ],
        ),
    ]
